apiVersion: v1
data:
  app-config.properties: |-
    kafka.sub=topic-mission-command
    kafka.sub.responder.loc.update=topic-responder-location-update
    kafka.pub=topic-mission-event
    kafka.pub.responder.update=topic-responder-command
    kafka.autocommit=true
    kafka.group.id=mission-service
    jdg.svc.name=datagrid-service
    jdg.app.name=datagrid-service
    jdg.app.user.name=demo
    jdg.app.user.password=demo
    jdg.port=11222
    http.host=localhost
    http.port=8080
    map.token=
kind: ConfigMap
metadata:
  name: mission-service
